const types = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_CHARACTERS_SUCCESS: 'GET_CHARACTERS_SUCCESS',
  GET_EPISODE: 'GET_EPISODE',
  GET_EPISODE_SUCCESS: 'GET_EPISODE_SUCCESS',
  MARK_FAVORITE: 'MARK_FAVORITE',
  CHANGE_LIST_VIEW_TYPE: 'CHANGE_LIST_VIEW_TYPE',
};

export default types;
